steps:
  # Paso 1: Compilar la imagen usando Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/api-loan-default'
      - '--builder'
      - 'gcr.io/buildpacks/builder:v1'

  # Paso 2: Deploy en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api-loan-default'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-loan-default'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'

images:
  - 'gcr.io/$PROJECT_ID/api-loan-default'

options:
  logging: CLOUD_LOGGING_ONLY
